# Generated by Django 3.0.4 on 2020-09-19 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=80)),
                ('Email', models.EmailField(blank=True, max_length=70, unique=True)),
                ('Credit', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField(blank=True, null=True)),
                ('Status', models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], default='Credit', max_length=80)),
                ('WhoUsers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WhoUser', to='cal.Users')),
                ('WhomUsers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WhomUser', to='cal.Users')),
            ],
        ),
    ]
